# : << 'EOF'
# Oh my tmux!
# 💛🩷💙🖤❤️🤍
# https://github.com/gpakosz/.tmux
# (‑●‑●)> dual licensed under the WTFPL v2 license and the MIT license,
#         without any warranty.
#         Copyright 2012— Gregory Pakosz (@gpakosz).

#----------------My Custom Stuff----------------------

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# Make the status line more pleasant.
set -g status-left ""
# set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '
set -g status-right "#[bg=#{@thm_teal},fg=#{@thm_crust}]#[reverse]#[noreverse] "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] #(curl -m 1 wttr.in?format=3 ; sleep 100)  " 
set -ag status-right "#{battery_status}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_date_time}"

set-window-option -g mode-style "bg=#{@thm_surface_1},fg=#{@thm_overlay_2},bold"



# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 200

# set-option -g default-shell /opt/homebrew/bin/nu
set-option -g default-shell /bin/zsh


set -g prefix ^A
set -g renumber-windows on       # renumber all windows 
set -g set-clipboard on          # use system clipboard
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g mouse on

bind ^X lock-server
bind ^C new-window -c "$HOME"
bind ^D detach
bind * list-clients

bind H previous-window
bind L next-window

bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind z resize-pane -Z
bind ^L refresh-client
bind l refresh-client
bind | split-window
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind '"' choose-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7
bind : command-prompt
bind * setw synchronize-panes
bind P set pane-border-status
bind c kill-pane
bind x swap-pane -D
bind S choose-session
bind R source-file ~/.config/tmux/tmux.conf
bind K send-keys "clear"\; send-keys "Enter"
bind-key -T copy-mode-vi v send-keys -X begin-selection

